print('Olá,vamos fazer o seu crachá de Dev personalizado!')
resposta_nome = input('Preciso que você primeiramente me diga seu nome:  ')
resposta_idade = input('Ótimo! agora me diga sua idade: ')
resposta_linguagem = input('Certo, preciso agora que você me diga sua linguagem de programação favorita: ')
print()
print('Certo,estamos criando seu crachá..')
input()
input('crachá criado com sucesso! Aperte ENTER para vizualizar seu crachá!')

print ('_______________')
print()
print('🧑‍💻 Crachá Dev')
print()
print(f'Nome: {resposta_nome}')
print(f'Idade: {resposta_idade}')
print(f'Linguagem favorita: {resposta_linguagem}')
print()
print('---------------') 