print('Olá,vamos fazer o seu crachá de Dev personalizado!')
resposta_nome = input('Preciso que você primeiramente me diga seu nome:  ')
resposta_idade = input('Ótimo! agora me diga sua idade: ')
resposta_linguagem = input('Certo, preciso agora que você me diga sua linguagem de programação favorita: ')
resposta_emoji = input('Por fim, escolha um emoji que te represente: ')

print()

print('Certo,estamos criando seu crachá..')
input('Pressione ENTER para continuar')
input('Crachá criado com sucesso! Pressione ENTER para visualizar!')

print()
print('____________________')
print()
print(f'{resposta_emoji} Crachá do Dev')
print('____________________')
print()
print(f'Nome: {resposta_nome}')
print(f'Idade: {resposta_idade}')
print(f'Linguagem favorita: {resposta_linguagem}')
print('____________________') 
